// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoBuff.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Org.Mpp2024.ProtocolBuffer {

  /// <summary>Holder for reflection information generated from ProtoBuff.proto</summary>
  public static partial class ProtoBuffReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoBuff.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoBuffReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9Qcm90b0J1ZmYucHJvdG8SGm9yZy5tcHAyMDI0LlByb3RvY29sQnVmZmVy",
            "IikKB0FjY291bnQSDAoEbmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSKR",
            "AQoEVHJpcBITCgtkZXN0aW5hdGlvbhgBIAEoCRIYChB0cmFuc3BvcnRDb21w",
            "YW55GAIgASgJEg0KBXByaWNlGAMgASgDEhYKDmF2YWlsYWJsZVNlYXRzGAQg",
            "ASgJEgwKBGRhdGUYBSABKAkSEQoJc3RhcnRIb3VyGAYgASgJEhIKCmZpbmlz",
            "aEhvdXIYByABKAkirQEKC1Jlc2VydmF0aW9uEhIKCmNsaWVudE5hbWUYASAB",
            "KAkSEwoLcGhvbmVOdW1iZXIYAiABKAkSDwoHdGlja2V0cxgDIAEoAxIuCgR0",
            "cmlwGAQgAygLMiAub3JnLm1wcDIwMjQuUHJvdG9jb2xCdWZmZXIuVHJpcBI0",
            "CgdhY2NvdW50GAUgAygLMiMub3JnLm1wcDIwMjQuUHJvdG9jb2xCdWZmZXIu",
            "QWNjb3VudCJICgpUcmlwRmlsdGVyEhMKC2Rlc3RpbmF0aW9uGAEgASgJEhEK",
            "CXN0YXJ0SG91chgCIAEoCRISCgpmaW5pc2hIb3VyGAMgASgJIu8DCgdSZXF1",
            "ZXN0Ej0KBHR5cGUYASABKA4yLy5vcmcubXBwMjAyNC5Qcm90b2NvbEJ1ZmZl",
            "ci5SZXF1ZXN0LlJlcXVlc3RUeXBlEjQKB2FjY291bnQYAiABKAsyIy5vcmcu",
            "bXBwMjAyNC5Qcm90b2NvbEJ1ZmZlci5BY2NvdW50Ei4KBHRyaXAYAyABKAsy",
            "IC5vcmcubXBwMjAyNC5Qcm90b2NvbEJ1ZmZlci5UcmlwEjwKC3Jlc2VydmF0",
            "aW9uGAQgASgLMicub3JnLm1wcDIwMjQuUHJvdG9jb2xCdWZmZXIuUmVzZXJ2",
            "YXRpb24SOgoKdHJpcEZpbHRlchgFIAEoCzImLm9yZy5tcHAyMDI0LlByb3Rv",
            "Y29sQnVmZmVyLlRyaXBGaWx0ZXIixAEKC1JlcXVlc3RUeXBlEgkKBUxPR0lO",
            "EAASCgoGTE9HT1VUEAESDAoIUkVHSVNURVIQAhIUChBNQUtFX1JFU0VSVkFU",
            "SU9OEAMSFAoQR0VUX0FMTF9BQ0NPVU5UUxAEEhAKDEdFVF9BTExfVFJJUBAF",
            "EhcKE0dFVF9BTExfUkVTRVJWQVRJT04QBhInCiNHRVRfQUxMX1RSSVBfQllf",
            "REVTVElOQVRJT05fRlJPTV9UTxAHEhAKDE1BS0VfQUNDT1VOVBAIIuUDCghS",
            "ZXNwb25zZRI/CgR0eXBlGAEgASgOMjEub3JnLm1wcDIwMjQuUHJvdG9jb2xC",
            "dWZmZXIuUmVzcG9uc2UuUmVzcG9uc2VUeXBlEjQKB2FjY291bnQYAiADKAsy",
            "Iy5vcmcubXBwMjAyNC5Qcm90b2NvbEJ1ZmZlci5BY2NvdW50Ei4KBHRyaXAY",
            "AyADKAsyIC5vcmcubXBwMjAyNC5Qcm90b2NvbEJ1ZmZlci5UcmlwEjwKC3Jl",
            "c2VydmF0aW9uGAQgAygLMicub3JnLm1wcDIwMjQuUHJvdG9jb2xCdWZmZXIu",
            "UmVzZXJ2YXRpb24SOgoKdHJpcEZpbHRlchgFIAMoCzImLm9yZy5tcHAyMDI0",
            "LlByb3RvY29sQnVmZmVyLlRyaXBGaWx0ZXIitwEKDFJlc3BvbnNlVHlwZRIJ",
            "CgVMT0dJThAAEgYKAk9LEAESCQoFRVJST1IQAhIKCgZVUERBVEUQAxIQCgxH",
            "RVRfQUxMX1RSSVAQBBIUChBNQUtFX1JFU0VSVkFUSU9OEAUSFAoQR0VUX0FM",
            "TF9BQ0NPVU5UUxAGEhYKEkdFVF9BTExfUkVTRVJWQVRJTxAHEicKI0dFVF9B",
            "TExfVFJJUF9CWV9ERVNUSU5BVElPTl9GUk9NX1RPEAhCCkIIQXBwUHJvdG9i",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Mpp2024.ProtocolBuffer.Account), global::Org.Mpp2024.ProtocolBuffer.Account.Parser, new[]{ "Name", "Password" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Mpp2024.ProtocolBuffer.Trip), global::Org.Mpp2024.ProtocolBuffer.Trip.Parser, new[]{ "Destination", "TransportCompany", "Price", "AvailableSeats", "Date", "StartHour", "FinishHour" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Mpp2024.ProtocolBuffer.Reservation), global::Org.Mpp2024.ProtocolBuffer.Reservation.Parser, new[]{ "ClientName", "PhoneNumber", "Tickets", "Trip", "Account" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Mpp2024.ProtocolBuffer.TripFilter), global::Org.Mpp2024.ProtocolBuffer.TripFilter.Parser, new[]{ "Destination", "StartHour", "FinishHour" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Mpp2024.ProtocolBuffer.Request), global::Org.Mpp2024.ProtocolBuffer.Request.Parser, new[]{ "Type", "Account", "Trip", "Reservation", "TripFilter" }, null, new[]{ typeof(global::Org.Mpp2024.ProtocolBuffer.Request.Types.RequestType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Org.Mpp2024.ProtocolBuffer.Response), global::Org.Mpp2024.ProtocolBuffer.Response.Parser, new[]{ "Type", "Account", "Trip", "Reservation", "TripFilter" }, null, new[]{ typeof(global::Org.Mpp2024.ProtocolBuffer.Response.Types.ResponseType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Account : pb::IMessage<Account>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Account> _parser = new pb::MessageParser<Account>(() => new Account());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Account> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Mpp2024.ProtocolBuffer.ProtoBuffReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Account() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Account(Account other) : this() {
      name_ = other.name_;
      password_ = other.password_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Account Clone() {
      return new Account(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Account);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Account other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Password != other.Password) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Account other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Trip : pb::IMessage<Trip>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Trip> _parser = new pb::MessageParser<Trip>(() => new Trip());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Trip> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Mpp2024.ProtocolBuffer.ProtoBuffReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Trip() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Trip(Trip other) : this() {
      destination_ = other.destination_;
      transportCompany_ = other.transportCompany_;
      price_ = other.price_;
      availableSeats_ = other.availableSeats_;
      date_ = other.date_;
      startHour_ = other.startHour_;
      finishHour_ = other.finishHour_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Trip Clone() {
      return new Trip(this);
    }

    /// <summary>Field number for the "destination" field.</summary>
    public const int DestinationFieldNumber = 1;
    private string destination_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Destination {
      get { return destination_; }
      set {
        destination_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "transportCompany" field.</summary>
    public const int TransportCompanyFieldNumber = 2;
    private string transportCompany_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TransportCompany {
      get { return transportCompany_; }
      set {
        transportCompany_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 3;
    private long price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    /// <summary>Field number for the "availableSeats" field.</summary>
    public const int AvailableSeatsFieldNumber = 4;
    private string availableSeats_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AvailableSeats {
      get { return availableSeats_; }
      set {
        availableSeats_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "date" field.</summary>
    public const int DateFieldNumber = 5;
    private string date_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Date {
      get { return date_; }
      set {
        date_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "startHour" field.</summary>
    public const int StartHourFieldNumber = 6;
    private string startHour_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StartHour {
      get { return startHour_; }
      set {
        startHour_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "finishHour" field.</summary>
    public const int FinishHourFieldNumber = 7;
    private string finishHour_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FinishHour {
      get { return finishHour_; }
      set {
        finishHour_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Trip);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Trip other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Destination != other.Destination) return false;
      if (TransportCompany != other.TransportCompany) return false;
      if (Price != other.Price) return false;
      if (AvailableSeats != other.AvailableSeats) return false;
      if (Date != other.Date) return false;
      if (StartHour != other.StartHour) return false;
      if (FinishHour != other.FinishHour) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Destination.Length != 0) hash ^= Destination.GetHashCode();
      if (TransportCompany.Length != 0) hash ^= TransportCompany.GetHashCode();
      if (Price != 0L) hash ^= Price.GetHashCode();
      if (AvailableSeats.Length != 0) hash ^= AvailableSeats.GetHashCode();
      if (Date.Length != 0) hash ^= Date.GetHashCode();
      if (StartHour.Length != 0) hash ^= StartHour.GetHashCode();
      if (FinishHour.Length != 0) hash ^= FinishHour.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Destination.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Destination);
      }
      if (TransportCompany.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TransportCompany);
      }
      if (Price != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Price);
      }
      if (AvailableSeats.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AvailableSeats);
      }
      if (Date.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Date);
      }
      if (StartHour.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(StartHour);
      }
      if (FinishHour.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(FinishHour);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Destination.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Destination);
      }
      if (TransportCompany.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TransportCompany);
      }
      if (Price != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Price);
      }
      if (AvailableSeats.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AvailableSeats);
      }
      if (Date.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Date);
      }
      if (StartHour.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(StartHour);
      }
      if (FinishHour.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(FinishHour);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Destination.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Destination);
      }
      if (TransportCompany.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TransportCompany);
      }
      if (Price != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Price);
      }
      if (AvailableSeats.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AvailableSeats);
      }
      if (Date.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Date);
      }
      if (StartHour.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StartHour);
      }
      if (FinishHour.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FinishHour);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Trip other) {
      if (other == null) {
        return;
      }
      if (other.Destination.Length != 0) {
        Destination = other.Destination;
      }
      if (other.TransportCompany.Length != 0) {
        TransportCompany = other.TransportCompany;
      }
      if (other.Price != 0L) {
        Price = other.Price;
      }
      if (other.AvailableSeats.Length != 0) {
        AvailableSeats = other.AvailableSeats;
      }
      if (other.Date.Length != 0) {
        Date = other.Date;
      }
      if (other.StartHour.Length != 0) {
        StartHour = other.StartHour;
      }
      if (other.FinishHour.Length != 0) {
        FinishHour = other.FinishHour;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Destination = input.ReadString();
            break;
          }
          case 18: {
            TransportCompany = input.ReadString();
            break;
          }
          case 24: {
            Price = input.ReadInt64();
            break;
          }
          case 34: {
            AvailableSeats = input.ReadString();
            break;
          }
          case 42: {
            Date = input.ReadString();
            break;
          }
          case 50: {
            StartHour = input.ReadString();
            break;
          }
          case 58: {
            FinishHour = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Destination = input.ReadString();
            break;
          }
          case 18: {
            TransportCompany = input.ReadString();
            break;
          }
          case 24: {
            Price = input.ReadInt64();
            break;
          }
          case 34: {
            AvailableSeats = input.ReadString();
            break;
          }
          case 42: {
            Date = input.ReadString();
            break;
          }
          case 50: {
            StartHour = input.ReadString();
            break;
          }
          case 58: {
            FinishHour = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Reservation : pb::IMessage<Reservation>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Reservation> _parser = new pb::MessageParser<Reservation>(() => new Reservation());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Reservation> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Mpp2024.ProtocolBuffer.ProtoBuffReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Reservation() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Reservation(Reservation other) : this() {
      clientName_ = other.clientName_;
      phoneNumber_ = other.phoneNumber_;
      tickets_ = other.tickets_;
      trip_ = other.trip_.Clone();
      account_ = other.account_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Reservation Clone() {
      return new Reservation(this);
    }

    /// <summary>Field number for the "clientName" field.</summary>
    public const int ClientNameFieldNumber = 1;
    private string clientName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientName {
      get { return clientName_; }
      set {
        clientName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "phoneNumber" field.</summary>
    public const int PhoneNumberFieldNumber = 2;
    private string phoneNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PhoneNumber {
      get { return phoneNumber_; }
      set {
        phoneNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "tickets" field.</summary>
    public const int TicketsFieldNumber = 3;
    private long tickets_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Tickets {
      get { return tickets_; }
      set {
        tickets_ = value;
      }
    }

    /// <summary>Field number for the "trip" field.</summary>
    public const int TripFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Org.Mpp2024.ProtocolBuffer.Trip> _repeated_trip_codec
        = pb::FieldCodec.ForMessage(34, global::Org.Mpp2024.ProtocolBuffer.Trip.Parser);
    private readonly pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.Trip> trip_ = new pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.Trip>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.Trip> Trip {
      get { return trip_; }
    }

    /// <summary>Field number for the "account" field.</summary>
    public const int AccountFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Org.Mpp2024.ProtocolBuffer.Account> _repeated_account_codec
        = pb::FieldCodec.ForMessage(42, global::Org.Mpp2024.ProtocolBuffer.Account.Parser);
    private readonly pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.Account> account_ = new pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.Account>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.Account> Account {
      get { return account_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Reservation);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Reservation other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ClientName != other.ClientName) return false;
      if (PhoneNumber != other.PhoneNumber) return false;
      if (Tickets != other.Tickets) return false;
      if(!trip_.Equals(other.trip_)) return false;
      if(!account_.Equals(other.account_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ClientName.Length != 0) hash ^= ClientName.GetHashCode();
      if (PhoneNumber.Length != 0) hash ^= PhoneNumber.GetHashCode();
      if (Tickets != 0L) hash ^= Tickets.GetHashCode();
      hash ^= trip_.GetHashCode();
      hash ^= account_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ClientName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientName);
      }
      if (PhoneNumber.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PhoneNumber);
      }
      if (Tickets != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Tickets);
      }
      trip_.WriteTo(output, _repeated_trip_codec);
      account_.WriteTo(output, _repeated_account_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ClientName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ClientName);
      }
      if (PhoneNumber.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PhoneNumber);
      }
      if (Tickets != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Tickets);
      }
      trip_.WriteTo(ref output, _repeated_trip_codec);
      account_.WriteTo(ref output, _repeated_account_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ClientName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientName);
      }
      if (PhoneNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PhoneNumber);
      }
      if (Tickets != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Tickets);
      }
      size += trip_.CalculateSize(_repeated_trip_codec);
      size += account_.CalculateSize(_repeated_account_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Reservation other) {
      if (other == null) {
        return;
      }
      if (other.ClientName.Length != 0) {
        ClientName = other.ClientName;
      }
      if (other.PhoneNumber.Length != 0) {
        PhoneNumber = other.PhoneNumber;
      }
      if (other.Tickets != 0L) {
        Tickets = other.Tickets;
      }
      trip_.Add(other.trip_);
      account_.Add(other.account_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ClientName = input.ReadString();
            break;
          }
          case 18: {
            PhoneNumber = input.ReadString();
            break;
          }
          case 24: {
            Tickets = input.ReadInt64();
            break;
          }
          case 34: {
            trip_.AddEntriesFrom(input, _repeated_trip_codec);
            break;
          }
          case 42: {
            account_.AddEntriesFrom(input, _repeated_account_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ClientName = input.ReadString();
            break;
          }
          case 18: {
            PhoneNumber = input.ReadString();
            break;
          }
          case 24: {
            Tickets = input.ReadInt64();
            break;
          }
          case 34: {
            trip_.AddEntriesFrom(ref input, _repeated_trip_codec);
            break;
          }
          case 42: {
            account_.AddEntriesFrom(ref input, _repeated_account_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TripFilter : pb::IMessage<TripFilter>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TripFilter> _parser = new pb::MessageParser<TripFilter>(() => new TripFilter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TripFilter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Mpp2024.ProtocolBuffer.ProtoBuffReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TripFilter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TripFilter(TripFilter other) : this() {
      destination_ = other.destination_;
      startHour_ = other.startHour_;
      finishHour_ = other.finishHour_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TripFilter Clone() {
      return new TripFilter(this);
    }

    /// <summary>Field number for the "destination" field.</summary>
    public const int DestinationFieldNumber = 1;
    private string destination_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Destination {
      get { return destination_; }
      set {
        destination_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "startHour" field.</summary>
    public const int StartHourFieldNumber = 2;
    private string startHour_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StartHour {
      get { return startHour_; }
      set {
        startHour_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "finishHour" field.</summary>
    public const int FinishHourFieldNumber = 3;
    private string finishHour_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FinishHour {
      get { return finishHour_; }
      set {
        finishHour_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TripFilter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TripFilter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Destination != other.Destination) return false;
      if (StartHour != other.StartHour) return false;
      if (FinishHour != other.FinishHour) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Destination.Length != 0) hash ^= Destination.GetHashCode();
      if (StartHour.Length != 0) hash ^= StartHour.GetHashCode();
      if (FinishHour.Length != 0) hash ^= FinishHour.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Destination.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Destination);
      }
      if (StartHour.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(StartHour);
      }
      if (FinishHour.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FinishHour);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Destination.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Destination);
      }
      if (StartHour.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(StartHour);
      }
      if (FinishHour.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(FinishHour);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Destination.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Destination);
      }
      if (StartHour.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StartHour);
      }
      if (FinishHour.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FinishHour);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TripFilter other) {
      if (other == null) {
        return;
      }
      if (other.Destination.Length != 0) {
        Destination = other.Destination;
      }
      if (other.StartHour.Length != 0) {
        StartHour = other.StartHour;
      }
      if (other.FinishHour.Length != 0) {
        FinishHour = other.FinishHour;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Destination = input.ReadString();
            break;
          }
          case 18: {
            StartHour = input.ReadString();
            break;
          }
          case 26: {
            FinishHour = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Destination = input.ReadString();
            break;
          }
          case 18: {
            StartHour = input.ReadString();
            break;
          }
          case 26: {
            FinishHour = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Mpp2024.ProtocolBuffer.ProtoBuffReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      type_ = other.type_;
      account_ = other.account_ != null ? other.account_.Clone() : null;
      trip_ = other.trip_ != null ? other.trip_.Clone() : null;
      reservation_ = other.reservation_ != null ? other.reservation_.Clone() : null;
      tripFilter_ = other.tripFilter_ != null ? other.tripFilter_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Org.Mpp2024.ProtocolBuffer.Request.Types.RequestType type_ = global::Org.Mpp2024.ProtocolBuffer.Request.Types.RequestType.Login;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Mpp2024.ProtocolBuffer.Request.Types.RequestType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "account" field.</summary>
    public const int AccountFieldNumber = 2;
    private global::Org.Mpp2024.ProtocolBuffer.Account account_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Mpp2024.ProtocolBuffer.Account Account {
      get { return account_; }
      set {
        account_ = value;
      }
    }

    /// <summary>Field number for the "trip" field.</summary>
    public const int TripFieldNumber = 3;
    private global::Org.Mpp2024.ProtocolBuffer.Trip trip_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Mpp2024.ProtocolBuffer.Trip Trip {
      get { return trip_; }
      set {
        trip_ = value;
      }
    }

    /// <summary>Field number for the "reservation" field.</summary>
    public const int ReservationFieldNumber = 4;
    private global::Org.Mpp2024.ProtocolBuffer.Reservation reservation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Mpp2024.ProtocolBuffer.Reservation Reservation {
      get { return reservation_; }
      set {
        reservation_ = value;
      }
    }

    /// <summary>Field number for the "tripFilter" field.</summary>
    public const int TripFilterFieldNumber = 5;
    private global::Org.Mpp2024.ProtocolBuffer.TripFilter tripFilter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Mpp2024.ProtocolBuffer.TripFilter TripFilter {
      get { return tripFilter_; }
      set {
        tripFilter_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(Account, other.Account)) return false;
      if (!object.Equals(Trip, other.Trip)) return false;
      if (!object.Equals(Reservation, other.Reservation)) return false;
      if (!object.Equals(TripFilter, other.TripFilter)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Org.Mpp2024.ProtocolBuffer.Request.Types.RequestType.Login) hash ^= Type.GetHashCode();
      if (account_ != null) hash ^= Account.GetHashCode();
      if (trip_ != null) hash ^= Trip.GetHashCode();
      if (reservation_ != null) hash ^= Reservation.GetHashCode();
      if (tripFilter_ != null) hash ^= TripFilter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Org.Mpp2024.ProtocolBuffer.Request.Types.RequestType.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (account_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Account);
      }
      if (trip_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Trip);
      }
      if (reservation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Reservation);
      }
      if (tripFilter_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(TripFilter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Org.Mpp2024.ProtocolBuffer.Request.Types.RequestType.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (account_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Account);
      }
      if (trip_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Trip);
      }
      if (reservation_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Reservation);
      }
      if (tripFilter_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(TripFilter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Org.Mpp2024.ProtocolBuffer.Request.Types.RequestType.Login) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (account_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Account);
      }
      if (trip_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Trip);
      }
      if (reservation_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Reservation);
      }
      if (tripFilter_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TripFilter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Org.Mpp2024.ProtocolBuffer.Request.Types.RequestType.Login) {
        Type = other.Type;
      }
      if (other.account_ != null) {
        if (account_ == null) {
          Account = new global::Org.Mpp2024.ProtocolBuffer.Account();
        }
        Account.MergeFrom(other.Account);
      }
      if (other.trip_ != null) {
        if (trip_ == null) {
          Trip = new global::Org.Mpp2024.ProtocolBuffer.Trip();
        }
        Trip.MergeFrom(other.Trip);
      }
      if (other.reservation_ != null) {
        if (reservation_ == null) {
          Reservation = new global::Org.Mpp2024.ProtocolBuffer.Reservation();
        }
        Reservation.MergeFrom(other.Reservation);
      }
      if (other.tripFilter_ != null) {
        if (tripFilter_ == null) {
          TripFilter = new global::Org.Mpp2024.ProtocolBuffer.TripFilter();
        }
        TripFilter.MergeFrom(other.TripFilter);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Org.Mpp2024.ProtocolBuffer.Request.Types.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            if (account_ == null) {
              Account = new global::Org.Mpp2024.ProtocolBuffer.Account();
            }
            input.ReadMessage(Account);
            break;
          }
          case 26: {
            if (trip_ == null) {
              Trip = new global::Org.Mpp2024.ProtocolBuffer.Trip();
            }
            input.ReadMessage(Trip);
            break;
          }
          case 34: {
            if (reservation_ == null) {
              Reservation = new global::Org.Mpp2024.ProtocolBuffer.Reservation();
            }
            input.ReadMessage(Reservation);
            break;
          }
          case 42: {
            if (tripFilter_ == null) {
              TripFilter = new global::Org.Mpp2024.ProtocolBuffer.TripFilter();
            }
            input.ReadMessage(TripFilter);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Org.Mpp2024.ProtocolBuffer.Request.Types.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            if (account_ == null) {
              Account = new global::Org.Mpp2024.ProtocolBuffer.Account();
            }
            input.ReadMessage(Account);
            break;
          }
          case 26: {
            if (trip_ == null) {
              Trip = new global::Org.Mpp2024.ProtocolBuffer.Trip();
            }
            input.ReadMessage(Trip);
            break;
          }
          case 34: {
            if (reservation_ == null) {
              Reservation = new global::Org.Mpp2024.ProtocolBuffer.Reservation();
            }
            input.ReadMessage(Reservation);
            break;
          }
          case 42: {
            if (tripFilter_ == null) {
              TripFilter = new global::Org.Mpp2024.ProtocolBuffer.TripFilter();
            }
            input.ReadMessage(TripFilter);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Request message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum RequestType {
        [pbr::OriginalName("LOGIN")] Login = 0,
        [pbr::OriginalName("LOGOUT")] Logout = 1,
        [pbr::OriginalName("REGISTER")] Register = 2,
        [pbr::OriginalName("MAKE_RESERVATION")] MakeReservation = 3,
        [pbr::OriginalName("GET_ALL_ACCOUNTS")] GetAllAccounts = 4,
        [pbr::OriginalName("GET_ALL_TRIP")] GetAllTrip = 5,
        [pbr::OriginalName("GET_ALL_RESERVATION")] GetAllReservation = 6,
        [pbr::OriginalName("GET_ALL_TRIP_BY_DESTINATION_FROM_TO")] GetAllTripByDestinationFromTo = 7,
        [pbr::OriginalName("MAKE_ACCOUNT")] MakeAccount = 8,
      }

    }
    #endregion

  }

  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Org.Mpp2024.ProtocolBuffer.ProtoBuffReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      type_ = other.type_;
      account_ = other.account_.Clone();
      trip_ = other.trip_.Clone();
      reservation_ = other.reservation_.Clone();
      tripFilter_ = other.tripFilter_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Org.Mpp2024.ProtocolBuffer.Response.Types.ResponseType type_ = global::Org.Mpp2024.ProtocolBuffer.Response.Types.ResponseType.Login;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Org.Mpp2024.ProtocolBuffer.Response.Types.ResponseType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "account" field.</summary>
    public const int AccountFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Org.Mpp2024.ProtocolBuffer.Account> _repeated_account_codec
        = pb::FieldCodec.ForMessage(18, global::Org.Mpp2024.ProtocolBuffer.Account.Parser);
    private readonly pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.Account> account_ = new pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.Account>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.Account> Account {
      get { return account_; }
    }

    /// <summary>Field number for the "trip" field.</summary>
    public const int TripFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Org.Mpp2024.ProtocolBuffer.Trip> _repeated_trip_codec
        = pb::FieldCodec.ForMessage(26, global::Org.Mpp2024.ProtocolBuffer.Trip.Parser);
    private readonly pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.Trip> trip_ = new pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.Trip>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.Trip> Trip {
      get { return trip_; }
    }

    /// <summary>Field number for the "reservation" field.</summary>
    public const int ReservationFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Org.Mpp2024.ProtocolBuffer.Reservation> _repeated_reservation_codec
        = pb::FieldCodec.ForMessage(34, global::Org.Mpp2024.ProtocolBuffer.Reservation.Parser);
    private readonly pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.Reservation> reservation_ = new pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.Reservation>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.Reservation> Reservation {
      get { return reservation_; }
    }

    /// <summary>Field number for the "tripFilter" field.</summary>
    public const int TripFilterFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Org.Mpp2024.ProtocolBuffer.TripFilter> _repeated_tripFilter_codec
        = pb::FieldCodec.ForMessage(42, global::Org.Mpp2024.ProtocolBuffer.TripFilter.Parser);
    private readonly pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.TripFilter> tripFilter_ = new pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.TripFilter>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Org.Mpp2024.ProtocolBuffer.TripFilter> TripFilter {
      get { return tripFilter_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if(!account_.Equals(other.account_)) return false;
      if(!trip_.Equals(other.trip_)) return false;
      if(!reservation_.Equals(other.reservation_)) return false;
      if(!tripFilter_.Equals(other.tripFilter_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Org.Mpp2024.ProtocolBuffer.Response.Types.ResponseType.Login) hash ^= Type.GetHashCode();
      hash ^= account_.GetHashCode();
      hash ^= trip_.GetHashCode();
      hash ^= reservation_.GetHashCode();
      hash ^= tripFilter_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Org.Mpp2024.ProtocolBuffer.Response.Types.ResponseType.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      account_.WriteTo(output, _repeated_account_codec);
      trip_.WriteTo(output, _repeated_trip_codec);
      reservation_.WriteTo(output, _repeated_reservation_codec);
      tripFilter_.WriteTo(output, _repeated_tripFilter_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Org.Mpp2024.ProtocolBuffer.Response.Types.ResponseType.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      account_.WriteTo(ref output, _repeated_account_codec);
      trip_.WriteTo(ref output, _repeated_trip_codec);
      reservation_.WriteTo(ref output, _repeated_reservation_codec);
      tripFilter_.WriteTo(ref output, _repeated_tripFilter_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Org.Mpp2024.ProtocolBuffer.Response.Types.ResponseType.Login) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      size += account_.CalculateSize(_repeated_account_codec);
      size += trip_.CalculateSize(_repeated_trip_codec);
      size += reservation_.CalculateSize(_repeated_reservation_codec);
      size += tripFilter_.CalculateSize(_repeated_tripFilter_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Org.Mpp2024.ProtocolBuffer.Response.Types.ResponseType.Login) {
        Type = other.Type;
      }
      account_.Add(other.account_);
      trip_.Add(other.trip_);
      reservation_.Add(other.reservation_);
      tripFilter_.Add(other.tripFilter_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Org.Mpp2024.ProtocolBuffer.Response.Types.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            account_.AddEntriesFrom(input, _repeated_account_codec);
            break;
          }
          case 26: {
            trip_.AddEntriesFrom(input, _repeated_trip_codec);
            break;
          }
          case 34: {
            reservation_.AddEntriesFrom(input, _repeated_reservation_codec);
            break;
          }
          case 42: {
            tripFilter_.AddEntriesFrom(input, _repeated_tripFilter_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Org.Mpp2024.ProtocolBuffer.Response.Types.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            account_.AddEntriesFrom(ref input, _repeated_account_codec);
            break;
          }
          case 26: {
            trip_.AddEntriesFrom(ref input, _repeated_trip_codec);
            break;
          }
          case 34: {
            reservation_.AddEntriesFrom(ref input, _repeated_reservation_codec);
            break;
          }
          case 42: {
            tripFilter_.AddEntriesFrom(ref input, _repeated_tripFilter_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Response message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum ResponseType {
        [pbr::OriginalName("LOGIN")] Login = 0,
        [pbr::OriginalName("OK")] Ok = 1,
        [pbr::OriginalName("ERROR")] Error = 2,
        [pbr::OriginalName("UPDATE")] Update = 3,
        [pbr::OriginalName("GET_ALL_TRIP")] GetAllTrip = 4,
        [pbr::OriginalName("MAKE_RESERVATION")] MakeReservation = 5,
        [pbr::OriginalName("GET_ALL_ACCOUNTS")] GetAllAccounts = 6,
        [pbr::OriginalName("GET_ALL_RESERVATIO")] GetAllReservatio = 7,
        [pbr::OriginalName("GET_ALL_TRIP_BY_DESTINATION_FROM_TO")] GetAllTripByDestinationFromTo = 8,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
