package org.mpp2024.RcpProtocol;


public enum RequestType {
    LOGIN, LOGOUT,REGISTER,MAKE_RESERVATION,GET_ALL_ACCOUNTS,GET_ALL_TRIP,GET_ALL_RESERVATION,GET_ALL_TRIP_BY_DESTINATION_FROM_TO,MAKE_ACCOUNT;
}
